<?php

namespace App\Swagger;

/**
 * @OA\Info(
 *      version="1.0.0",
 *      title="My API Documentation",
 *      description="This is the API documentation generated by Swagger for my Laravel project",
 *      @OA\Contact(
 *          email="youremail@example.com"
 *      ),
 * )
 *
 * @OA\Server(
 *      url=L5_SWAGGER_CONST_HOST,
 *      description="API Server"
 * )
 */
class OpenApi {}
